services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: timescale/timescaledb:latest-pg12
    ports:
    - 5432:5432/tcp
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090/tcp
    volumes:
    - ./sample-docker-prometheus:/etc/prometheus/prometheus:ro
  promscale-connector:
    build:
      context: .
    command: -db-ssl-mode=allow
    restart: on-failure
    depends_on:
    - db
    - prometheus
    environment:
      TS_PROM_LOG_LEVEL: debug
      TS_PROM_DB_CONNECT_RETRIES: 10
      TS_PROM_DB_HOST: db
      TS_PROM_DB_PASSWORD: postgres
      TS_PROM_DB_NAME: postgres
      TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
    image: timescale/promscale:latest
    ports:
    - 9201:9201/tcp
version: '3.0'
