apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: "promscale-connector"
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: "promscale-connector"
    app.kubernetes.io/component: "connector"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.upgradeStrategy }}
  selector:
    matchLabels:
      app: {{ template "promscale.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "promscale.fullname" . }}
        chart: {{ template "promscale.chart" . }}
        release: {{ .Release.Name }}
        app.kubernetes.io/name: "promscale-connector"
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/part-of: "promscale-connector"
        app.kubernetes.io/component: "connector"
      annotations: 
        checksum/config: {{ printf "%s" .Values.connection | sha256sum -}}
        {{- if .Values.prometheus.annotations }}
        {{- .Values.prometheus.annotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: promscale-connector
          args:
          {{- with .Values.extraArgs }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- if .Values.extraEnv }}
          env:
            {{- range $.Values.extraEnv }}
            - name: {{ .name }}
              value: {{ tpl (.value | quote) $ }}
            {{- end }}
          {{- end }}
          envFrom:
          - secretRef:
              {{- $secretName := ternary (include "promscale.fullname" .) .Values.connectionSecretName (eq .Values.connectionSecretName "") }}
              name: {{ tpl $secretName . }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9201
              name: metrics-port
            - containerPort: 9202
              name: otel-port
      serviceAccountName: {{ template "promscale.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
