apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
{{ include "promscale-helm.labels" . | nindent 4 }}
  {{- if .Values.annotations }}
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.upgradeStrategy }}
  selector:
    matchLabels:
      app: {{ include "promscale.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "promscale-helm.labels" . | indent 8 }}
      annotations:
        checksum/connection: {{ printf "%s" .Values.connection | sha256sum }}
        checksum/config: {{ printf "%s" .Values.config | sha256sum }}
        prometheus.io/port: '9201'
        prometheus.io/path: '/metrics'
        prometheus.io/scrape: {{ not .Values.serviceMonitor.enabled | quote }}
        {{- if .Values.podAnnotations }}
        {{- range $key, $value := .Values.podAnnotations }}
          {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: promscale
          args:
          - "-config=/etc/promscale/config.yaml"
          {{- with .Values.extraArgs }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          env:
            - name: TOBS_TELEMETRY_INSTALLED_BY
              value: "promscale"
            - name: "TOBS_TELEMETRY_VERSION"
              value: "{{ .Chart.Version }}"
          {{- if .Values.extraEnv }}
            {{- range $.Values.extraEnv }}
            - name: {{ .name }}
              value: {{ tpl (.value | quote) $ }}
            {{- end }}
          {{- end }}
          envFrom:
          - secretRef:
              {{- $secretName := ternary (include "promscale.fullname" .) .Values.connectionSecretName (eq .Values.connectionSecretName "") }}
              name: {{ tpl $secretName . }}
          {{- if .Values.extraEnvFrom }}
          {{ toYaml $.Values.extraEnvFrom | nindent 10 }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9201
              name: metrics-port
            - containerPort: 9202
              name: otel-port
          readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: configs
              mountPath: /etc/promscale/
      volumes:
        - name: configs
          configMap:
            name: {{ include "promscale.fullname" . }}
      serviceAccountName: {{ include "promscale.fullname" . }}
      automountServiceAccountToken: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
