{{- if or .Values.service.prometheus.enabled .Values.service.openTelemetry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ include "promscale.namespace" . }}
  labels:
{{ include "promscale-helm.labels" . | indent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ include "promscale.fullname" . }}
  type: {{ .Values.service.type }}
  ports:
  {{ if .Values.service.prometheus.enabled }}
  - name: metrics-port
    port: {{ .Values.service.prometheus.port }}
    targetPort: metrics-port
    protocol: TCP
  {{- end }}
  {{ if .Values.service.openTelemetry.enabled }}
  - name: otel-port
    port: {{ .Values.service.openTelemetry.port }}
    targetPort: otel-port
    protocol: TCP
  {{- end }}
{{- end }}
