---
# Source: promscale/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.13.0
    release: promscale
    heritage: Helm
    app.kubernetes.io/name: "promscale"
    app.kubernetes.io/version: 0.13.0
    app.kubernetes.io/component: "connector"
---
# Source: promscale/templates/secret-connection.yaml
apiVersion: v1
kind: Secret
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.13.0
    release: promscale
    heritage: Helm
    app.kubernetes.io/name: "promscale"
    app.kubernetes.io/version: 0.13.0
    app.kubernetes.io/component: "connector"
stringData:
  PROMSCALE_DB_PORT: "5432"
  PROMSCALE_DB_HOST: "timescaledb.default.svc.cluster.local"
  PROMSCALE_DB_NAME: "tsdb"
  PROMSCALE_DB_SSL_MODE: "require"
---
# Source: promscale/templates/svc-promscale.yaml
apiVersion: v1
kind: Service
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.13.0
    release: promscale
    heritage: Helm
    app.kubernetes.io/name: "promscale"
    app.kubernetes.io/version: 0.13.0
    app.kubernetes.io/component: "connector"
spec:
  selector:
    app: promscale
  type: ClusterIP
  ports:
  
  - name: metrics-port
    port: 9201
    targetPort: metrics-port
    protocol: TCP
  
  - name: otel-port
    port: 9202
    targetPort: otel-port
    protocol: TCP
---
# Source: promscale/templates/deployment-promscale.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promscale
  namespace: default
  labels:

    app: promscale
    chart: promscale-0.13.0
    release: promscale
    heritage: Helm
    app.kubernetes.io/name: "promscale"
    app.kubernetes.io/version: 0.13.0
    app.kubernetes.io/component: "connector"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: promscale
      release: promscale
  template:
    metadata:
      labels:
        app: promscale
        chart: promscale-0.13.0
        release: promscale
        heritage: Helm
        app.kubernetes.io/name: "promscale"
        app.kubernetes.io/version: 0.13.0
        app.kubernetes.io/component: "connector"
      annotations:
        checksum/connection: ff05ff54cbc0eadd9ce97781ed753f30c19ece1aa39b35d2eb5a70ad656daf69
        checksum/config: a1171a41877cc559fe699480d7c9bc731055fde6ccbe0b47e5c9a279cfe38962
        prometheus.io/port: '9201'
        prometheus.io/path: '/metrics'
        prometheus.io/scrape: "true"
    spec:
      containers:
        - image: timescale/promscale:0.13.0
          imagePullPolicy: IfNotPresent
          name: promscale
          args:
          - "-config=/etc/promscale/config.yaml"
          env:
            - name: TOBS_TELEMETRY_INSTALLED_BY
              value: "promscale"
            - name: "TOBS_TELEMETRY_VERSION"
              value: "0.13.0"
          envFrom:
          - secretRef:
              name: promscale
          ports:
            - containerPort: 9201
              name: metrics-port
            - containerPort: 9202
              name: otel-port
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: metrics-port
              scheme: HTTP
            periodSeconds: 15
            timeoutSeconds: 15
          volumeMounts:
            - name: configs
              mountPath: /etc/promscale/
      volumes:
        - name: configs
          configMap:
            name: promscale
      serviceAccountName: promscale
---
# Source: promscale/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
    chart: promscale-0.13.0
    release: promscale
    heritage: Helm
    app.kubernetes.io/name: "promscale"
    app.kubernetes.io/version: 0.13.0
    app.kubernetes.io/component: "connector"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-delete
    "helm.sh/hook-weight": "0"
data:
  config.yaml: |

    startup.dataset.config: |
      metrics:
        compress_data: true
        default_retention_period: 90d
      traces:
        default_retention_period: 30d
