version: '3.0'

services:
  db:
    # TODO (james): replace this when Promscale extension 0.7.0 published
    image: ghcr.io/timescale/dev_promscale_extension:jg-time-based-epoch-ts2-pg14
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  prometheus1:
    image: prom/prometheus:latest
    ports:
      - 9091:9090/tcp
    volumes:
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml:ro

  prometheus2:
    image: prom/prometheus:latest
    ports:
      - 9092:9090/tcp
    volumes:
      - ./prometheus2.yml:/etc/prometheus/prometheus.yml:ro

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093/tcp

  promscale-connector1:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus1
    volumes:
      - ${PWD}/../promscale_prometheus.yml:/prometheus.yml
      - ${PWD}/../rules.yml:/rules.yml
      - ${PWD}/../alerts.yml:/alerts.yml
    environment:
      PROMSCALE_METRICS_HIGH_AVAILABILITY: true
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
      PROMSCALE_METRICS_RULES_CONFIG_FILE: /prometheus.yml
      PROMSCALE_STARTUP_UPGRADE_PRERELEASE_EXTENSIONS: true

  promscale-connector2:
    image: timescale/promscale:latest
    ports:
      - 9202:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus2
    volumes:
      - ${PWD}/../promscale_prometheus.yml:/prometheus.yml
      - ${PWD}/../rules.yml:/rules.yml
      - ${PWD}/../alerts.yml:/alerts.yml
    environment:
      PROMSCALE_METRICS_HIGH_AVAILABILITY: true
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
      PROMSCALE_METRICS_RULES_CONFIG_FILE: /prometheus.yml
      PROMSCALE_STARTUP_UPGRADE_PRERELEASE_EXTENSIONS: true

  node_exporter:
    image: quay.io/prometheus/node-exporter
    ports:
      - "9100:9100"
