version: '3.0'

services:
  db:
    #TODO (james): replace with up-to-date timescale/timescaledb-ha image when it's ready
    image: ghcr.io/timescale/dev_promscale_extension:jg-ha-dockerfile-ts2-pg14
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: timescale

  prometheus1:
    image: prom/prometheus:latest
    ports:
      - 9091:9090/tcp
    volumes:
      - ./prometheus1.yml:/etc/prometheus/prometheus.yml:ro

  prometheus2:
    image: prom/prometheus:latest
    ports:
      - 9092:9090/tcp
    volumes:
      - ./prometheus2.yml:/etc/prometheus/prometheus.yml:ro

  promscale-connector1:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus1
    environment:
      PROMSCALE_METRICS_HIGH_AVAILABILITY: true
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_DB_HOST: db
      PROMSCALE_DB_PASSWORD: postgres
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_SSL_MODE: allow

  promscale-connector2:
    image: timescale/promscale:latest
    ports:
      - 9202:9201/tcp
    build:
      context: .
    restart: on-failure
    depends_on:
      - db
      - prometheus2
    environment:
      PROMSCALE_METRICS_HIGH_AVAILABILITY: true
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_DB_HOST: db
      PROMSCALE_DB_PASSWORD: postgres
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_SSL_MODE: allow
