apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "connector.fullname" . }}
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "connector.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "connector.fullname" . }}
      {{ if .Values.prometheus.enabled }}
      annotations: {{ .Values.prometheus.annotations | toYaml | nindent 8 }}
      {{ end }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: promscale-connector
          {{- if .Values.args }}
          args:
            {{- range .Values.args }}
              - {{ . }}
            {{- end }}
          {{- end}}
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9201
              name: connector-port
          env:
            - name: TS_PROM_DB_PORT
              value: {{ .Values.connection.port | quote }}
            - name: TS_PROM_DB_USER
              value: {{ .Values.connection.user }}
            - name: TS_PROM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.connection.password.secretTemplate . }}
                  key: {{ .Values.connection.user }}
            - name: TS_PROM_DB_HOST
              value: {{ tpl .Values.connection.host.nameTemplate . }}
            - name: TS_PROM_DB_NAME
              value: {{ .Values.connection.dbName }}
            - name: TS_PROM_DB_SSL_MODE
              value: {{ .Values.connection.sslMode }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
