version: '3.0'

services:
  timescaledb:
    # TODO change to 15 when the new HA image is available
    image: timescale/timescaledb-ha:pg14-latest
    restart: on-failure
    ports:
      - 5432:5432/tcp
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: tsdb
      POSTGRES_HOST_AUTH_METHOD: trust

  prometheus:
    image: prom/prometheus:latest
    restart: on-failure
    depends_on:
     - promscale
    ports:
      - 9090:9090/tcp
    volumes:
      - ${PWD}/../prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:latest
    restart: on-failure
    ports:
      - 9093:9093/tcp

  promscale:
    image: timescale/promscale:latest
    restart: on-failure
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    depends_on:
      - timescaledb
    volumes:
      - ${PWD}/../promscale_prometheus.yml:/prometheus.yml
      - ${PWD}/../rules.yml:/rules.yml
      - ${PWD}/../alerts.yml:/alerts.yml
    environment:
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/tsdb?sslmode=allow
      PROMSCALE_METRICS_RULES_CONFIG_FILE: /prometheus.yml
      PROMSCALE_PKG: "docker-quick-start"

  collector:
    image: "otel/opentelemetry-collector-contrib:0.63.1"
    restart: on-failure
    command: [ "--config=/etc/otel-collector-config.yml" ]
    depends_on:
      - promscale
    ports:
      - 14268:14268/tcp # jaeger http
      - 4317:4317/tcp
      - 4318:4318/tcp
    volumes:
      - ${PWD}/../otel-collector-config.yml:/etc/otel-collector-config.yml

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.39.0
    restart: on-failure
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      METRICS_STORAGE_TYPE: prometheus
      GRPC_STORAGE_SERVER: promscale:9202
      PROMETHEUS_SERVER_URL: "http://promscale:9201"

    depends_on:
    - timescaledb
    - promscale
    ports:
      - "16686:16686"

  grafana:
    image: timescale/promscale-demo-grafana
    restart: on-failure
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    depends_on:
      - timescaledb
      - jaeger-all-in-one

  node_exporter:
    image: quay.io/prometheus/node-exporter
    restart: on-failure
    ports:
      - "9100:9100"

  upper:
    image: timescale/promscale-demo-upper
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5054:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  lower:
    image: timescale/promscale-demo-lower
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5053:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318

  special:
    image: timescale/promscale-demo-special
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5052:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  digit:
    image: timescale/promscale-demo-digit
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5051:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  generator:
    image: timescale/promscale-demo-generator
    restart: on-failure
    depends_on:
      - upper
      - lower
      - special
      - digit
    ports:
      - 5050:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  load:
    image: timescale/promscale-demo-load
    restart: on-failure
    depends_on:
      - generator

volumes:
  timescaledb-data:
  grafana-data:
