version: '3.0'

services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 5432:5432/tcp
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: otel_demo
      POSTGRES_HOST_AUTH_METHOD: trust

  prometheus:
    image: prom/prometheus:latest
    depends_on:
     - promscale
    ports:
      - 9090:9090/tcp
    volumes:
      - ${PWD}/../prometheus.yml:/etc/prometheus/prometheus.yml

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093/tcp

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    restart: on-failure
    depends_on:
      - timescaledb
    volumes:
      - ${PWD}/../promscale_prometheus.yml:/prometheus.yml
      - ${PWD}/../rules.yml:/rules.yml
      - ${PWD}/../alerts.yml:/alerts.yml
    environment:
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/otel_demo?sslmode=allow
      PROMSCALE_TELEMETRY_TRACE_JAEGER_ENDPOINT: "http://collector:14268/api/traces"
      PROMSCALE_TELEMETRY_TRACE_SAMPLING_RATIO: "0.1"
      PROMSCALE_METRICS_RULES_CONFIG_FILE: /prometheus.yml

  collector:
    platform: linux/amd64
    image: "timescale/promscale-demo-collector"
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    depends_on:
      - promscale
    ports:
      - 14268:14268/tcp # jaeger http
      - 4317:4317/tcp
      - 4318:4318/tcp

  jaeger:
    image: jaegertracing/jaeger-query:1.33.0
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
    command: [
      "--grpc-storage.server=promscale:9202",
    ]
    ports:
      - "16686:16686"

  grafana:
    image: timescale/promscale-demo-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    restart: on-failure
    depends_on:
      - timescaledb
      - jaeger

  node_exporter:
    image: quay.io/prometheus/node-exporter
    ports:
      - "9100:9100"

  upper:
    image: timescale/promscale-demo-upper
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5054:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  lower:
    image: jamesgresql/opentelemetry-demo_lower:0.2
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5053:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4318

  special:
    image: timescale/promscale-demo-special
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5052:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317
  
  digit:
    image: timescale/promscale-demo-digit
    restart: on-failure
    depends_on:
      - collector
    ports:
      - 5051:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  generator:
    image: timescale/promscale-demo-generator
    restart: on-failure
    depends_on:
      - upper
      - lower
      - special
      - digit
    ports:
      - 5050:5000/tcp
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=collector:4317

  load:
    image: timescale/promscale-demo-load
    restart: on-failure
    depends_on:
      - generator
    deploy:
      mode: replicated
      replicas: 3

volumes:
  timescaledb-data:
  grafana-data: