name: Docker Compose tests

on:
  push:
    branches: [master, main, force_test, release-*]
  pull_request:
    branches: [master, main, force_test, release-*]

env:
  golang-version: '1.15'

jobs:

  build:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go ${{ env.golang-version }}
      uses: actions/setup-go@v2.1.5
      with:
        go-version: ${{ env.golang-version }}
      id: go

    - name: Test docker-compose setup referenced in docs
      run: ./docker-compose/test.sh
      shell: bash

    - name: Test high-availability docker-compose setup
      run: ./docker-compose/high-availability/test.sh
      shell: bash
