name: End-to-end test

on:
  push:
    branches: [master, main, force_test, release-*, staging, trying]
  pull_request:
    branches: [master, main, force_test, release-*]

jobs:

  build:
    name: Bash End-to-End Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test against TimescaleDB 2.x without Promscale extension (pg13)
      run: ./scripts/end_to_end_tests.sh timescale/timescaledb:latest-pg13
      shell: bash

    - name: Test against TimescaleDB 2.x with Promscale extension (pg13)
      run: ./scripts/end_to_end_tests.sh timescaledev/promscale-extension:latest-ts2-pg13
      shell: bash

    - name: Test against TimescaleDB 2.x with Promscale extension (pg12)
      run: ./scripts/end_to_end_tests.sh timescaledev/promscale-extension:latest-ts2-pg12
      shell: bash

    - name: Test against TimescaleDB 1.x with Promscale extension (pg12)
      run: ./scripts/end_to_end_tests.sh timescaledev/promscale-extension:latest-ts1-pg12
      shell: bash

    - name: Test against first supported
      run: ./scripts/end_to_end_tests.sh timescale/timescaledb:1.7.4-pg12
      shell: bash

  test-helm-chart:
    name: Test helm-chart template generation
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test helm chart static generation
      run: ./scripts/generate-deploy-script.sh