name: Helm Charts

on:
  push:
    branches: [master, main, force_test, release-*, staging, trying]
    tags: ['*']
  pull_request:
    branches: [master, main, force_test, release-*]

env:
  helm-version: v3.8.2

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Test helm chart static generation
      run: ./scripts/generate-deploy-script.sh

    - name: check if alerts were propagated to helm chart
      run: |
        make generate-helm --always-make
        git diff --exit-code

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.0
        with:
          version: ${{ env.helm-version }}

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          # FIXME(onprem): Remove this once chart-testing-action has a new release with ct v3.6.0 by default.
          version: v3.6.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install TimescaleDB in the cluster
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add timescale 'https://charts.timescale.com'
          helm repo update
          helm install \
            --set replicaCount=1 \
            timescaledb timescale/timescaledb-single
          kubectl rollout status statefulset timescaledb

      - name: Run chart-testing (install)
        run: |
          PGPASSWORD_POSTGRES=$(kubectl \
            get secret \
            --namespace default \
            timescaledb-credentials \
            -o jsonpath="{.data.PATRONI_SUPERUSER_PASSWORD}" | \
            base64 --decode \
          )
          ct install \
            --config ct.yaml \
            --helm-extra-set-args="--set=connection.uri=postgres://postgres:$PGPASSWORD_POSTGRES@timescaledb.default.svc.cluster.local:5432/postgres?sslmode=require"

  publish-chart:
    runs-on: ubuntu-latest
    needs: [generate, lint-test]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.0
        with:
          version: ${{ env.helm-version }}

      - name: Create package
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_SECRET_ACCESS_KEY }}
        run: |
            mkdir -p chart_release
            helm package deploy/helm-chart -d chart_release/
            helm plugin install https://github.com/hypnoglow/helm-s3.git          
            helm repo add tscharts s3://charts.timescale.com
            helm s3 push chart_release/* tscharts --acl public-read --relative --dry-run

      - name: push package
        env:
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ORG_AWS_HELM_CHART_BUCKET_SECRET_ACCESS_KEY }}
        run: |
          helm s3 push chart_release/* tscharts --acl public-read --relative
